name: Build
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '30 9 22 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  archlinux-aarch64:
    runs-on: ubuntu-24.04-arm
    outputs: &archlinux-outputs
      digest: ${{ fromJSON(steps.bake.outputs.metadata)[github.job]['containerimage.digest'] }}
    steps: &archlinux-steps
      - &metadata-action
        uses: docker/metadata-action@v6.0.0
        id: meta
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index
        with:
          bake-target: ${{ github.job }}
          images: ${{ vars.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch,enable={{is_not_default_branch}}
            type=ref,event=tag
            type=ref,event=pr
            type=schedule,pattern={{date 'YYYYMMDD'}}
      - uses: docker/setup-buildx-action@v4.0.0
      - uses: docker/login-action@v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/bake-action@v7.0.0
        id: bake
        with:
          targets: ${{ github.job }}
          files: |
            docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file-annotations }}
            cwd://${{ steps.meta.outputs.bake-file-labels }}
          set: |
            ${{ github.job }}.output=type=image,push=true,push-by-digest=true
            ${{ github.job }}.tags=${{ vars.IMAGE_NAME }}

  archlinux-armv7h:
    runs-on: ubuntu-24.04-arm
    outputs: *archlinux-outputs
    steps: *archlinux-steps

  archlinux-x86_64:
    runs-on: ubuntu-24.04
    outputs: *archlinux-outputs
    steps: *archlinux-steps

  merge-images:
    runs-on: ubuntu-slim
    needs:
      - archlinux-aarch64
      - archlinux-armv7h
      - archlinux-x86_64
    steps:
      - *metadata-action
      - uses: docker/login-action@v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge images
        run: |
          mapfile -t -d $'\0' args < \
            <(jq --raw-output0 '.annotations[] |= ["--annotation", .] | .tags[] |= ["--tag", .] | pick(.annotations, .tags) | flatten | .[]' <<< "$METADATA_JSON")
          mapfile -t -d $'\0' -O "${#args[@]}" args < \
            <(jq --raw-output0 '"\(env.IMAGE_NAME)@\(.[].outputs.digest)"' <<< "$NEEDS_JSON")
          printf -- '- %s\n' "${args[@]}"
          docker buildx imagetools create "${args[@]}"
        env:
          IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          METADATA_JSON: ${{ steps.meta.outputs.json }}
          NEEDS_JSON: ${{ toJSON(needs) }}
